const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict'),path=require('node:path');
const project=process.argv[2] || __dirname;
const root=path.join(project,'Js')+path.sep;
const list={innerHTML:'',addEventListener(){},querySelectorAll(){return []}};
const doc={getElementById(id){return id==='historicoLista'?list:null},querySelector(){return null},querySelectorAll(){return []},addEventListener(){}};
const ctx=vm.createContext({document:doc,window:{addEventListener(){}},console,Intl,Date,hojeIso:()=> '2026-10-01'});
vm.runInContext(fs.readFileSync(root+'historico.js','utf8'),ctx);
vm.runInContext("registros=[{id:1,glicemia:110,dose:0,hora:'12:00',data:'01/10/2026',dataIso:'2026-10-01',refeicao:'Almoço',observacao:''}]; atualizarHistorico()",ctx);
assert.ok(list.innerHTML.includes('110 mg/dL'));
vm.runInContext("registros[0].observacao='Fixture <script>alert(1)</script>'; atualizarHistorico()",ctx);
assert.ok(list.innerHTML.includes('id="observacao-0"'));
assert.ok(list.innerHTML.includes('aria-controls="observacao-0"'));
assert.ok(list.innerHTML.includes('&lt;script&gt;alert(1)&lt;/script&gt;'));
assert.ok(!list.innerHTML.includes('<script>'));
console.log('PASS: history with observations renders and escapes HTML.');
const elements={};
for(const id of ['inputHgtAtual','calcResultado','calcValor','calcClassificacao','calcErro','configPerfil','btnCalcular']) elements[id]={value:'',style:{},addEventListener(type,cb){this[type]=cb;}};
let load;
const ctx2=vm.createContext({document:{getElementById:id=>elements[id]||null},window:{addEventListener(type,cb){if(type==='load')load=cb}},localStorage:{getItem(key){return key==='profile'?JSON.stringify({hgtAlvo:100,fatorSensibilidade:50}):null}},console});
vm.runInContext(fs.readFileSync(root+'Calculadora.js','utf8'),ctx2); load();
elements.inputHgtAtual.value='1200'; elements.inputHgtAtual.input();
assert.equal(String(elements.inputHgtAtual.value),'1200');
assert.equal(elements.calcValor.textContent,'22,0 U');
elements.inputHgtAtual.value='180'; elements.inputHgtAtual.input();
assert.equal(elements.calcValor.textContent,'1,6 U');
const html=fs.readFileSync(path.join(project,'Calculadora.html'),'utf8');
const inputTag=html.match(/<input\b[^>]*id="inputHgtAtual"[^>]*>/)[0];
assert.ok(!/\bmax\s*=/.test(inputTag),'HTML must not cap HGT input silently at 600');
console.log('PASS: calculator preserves HGT 1200 and existing formula for normal values.');
console.log('No accounts or network requests were used.');
