// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260929044038_SincronizaComFront")]
    partial class SincronizaComFront
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.RegistroGlicemia", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                b.Property<DateOnly>("Data").HasColumnType("date");
                b.Property<int>("Dose").HasColumnType("int");
                b.Property<int?>("Glicemia").HasColumnType("int");
                b.Property<bool>("GlicemiaAcimaDoLimite").HasColumnType("tinyint(1)");
                b.Property<TimeSpan>("Hora").HasColumnType("time(6)");
                b.Property<string>("Observacao").HasMaxLength(500).HasColumnType("varchar(500)");
                b.Property<string>("Refeicao").IsRequired().HasColumnType("longtext");
                b.Property<int>("UsuarioId").HasColumnType("int");
                b.HasKey("Id");
                b.HasIndex("UsuarioId");
                b.ToTable("RegistrosGlicemia");
            });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                b.Property<bool>("AceitouTermos").HasColumnType("tinyint(1)");
                b.Property<bool>("Ativo").HasColumnType("tinyint(1)");
                b.Property<string>("Celular").HasColumnType("longtext");
                b.Property<bool>("ConsentimentoResponsavel").HasColumnType("tinyint(1)");
                b.Property<bool>("ConsentiuDadosSaude").HasColumnType("tinyint(1)");
                b.Property<DateTime?>("DataConsentimento").HasColumnType("datetime(6)");
                b.Property<string>("Email").IsRequired().HasColumnType("varchar(255)");
                b.Property<bool>("EmailConfirmado").HasColumnType("tinyint(1)");
                b.Property<int>("FatorSensibilidade").HasColumnType("int");
                b.Property<int>("HgtAlvo").HasColumnType("int");
                b.Property<int?>("Idade").HasColumnType("int");
                b.Property<string>("Name").IsRequired().HasColumnType("longtext");
                b.Property<string>("ResponsavelNome").IsRequired(false).HasColumnType("longtext");
                b.Property<string>("Role").IsRequired().HasColumnType("longtext");
                b.Property<string>("Senha").IsRequired().HasColumnType("longtext");
                b.Property<string>("TipoDiabetes").IsRequired().HasColumnType("longtext");
                b.HasKey("Id");
                b.HasIndex("Email").IsUnique();
                b.ToTable("Usuarios");
            });

            modelBuilder.Entity("Domain.Entities.RegistroGlicemia", b =>
            {
                b.HasOne("Domain.Entities.Usuario", "Usuario")
                    .WithMany("RegistroGlicemia")
                    .HasForeignKey("UsuarioId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Usuario");
            });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
            {
                b.Navigation("RegistroGlicemia");
            });
#pragma warning restore 612, 618
        }
    }
}
